# Generated by Django 5.2.4 on 2025-07-18 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_vaga_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['-data_publication'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AddField(
            model_name='vaga',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaga',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USR', 'Usuário'), ('RH', 'Recursos Humanos')], default='USR', max_length=3),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='data_publication',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
